### ISSUE TITLE
Didn't work for me in betacraft

### ISSUE THREAD

**Issue by sulphurbestgirl** [MCLegoMan/ST-3-Saving#1]
I was put the folder into the jar the best I could, but when I try to play it I get an error message saying Error code 7 (ERRCONFIG): Couldn't determine the launch method for your JAR. Configure your version configuration file with saving.info
no such file could be found in the jar or the mod

**Comment by mclegoman** [comment]
Thanks for your report!
- **How exactly are you putting the files into the jar?**
    - _I recommend using something like WinRAR, to copy from the .zip to the root of the .jar._
- **Could you provide any logs if possible?**

_I'll try and get betacraft running later to test, but afaik we did get it to work on betacraft when we were making it._

**Comment by sulphurbestgirl** [comment]
it worked with that method, 7zip didn't let me add files to the jar like WinRAR does so I tried extracting everything then putting it into a folder, making the folder a zip then changing the .zip to .jar

**Comment by mclegoman** [comment]
Sweet as! I'll add a note to the release page saying that WinRAR is recommended.
